### ISSUE TITLE
XamStorage.Exceptions.DirectoryNotFoundException

### ISSUE THREAD

**Issue by rex232** [DuckArne/XamStorage.Library#4]
Hi, I got an error when save a file on iOS simulator.  do i need to set any permission ? Please advise, many thanks.

{XamStorage.Exceptions.DirectoryNotFoundException: Directory does not exist: /Users/rex/Library/Developer/CoreSimulator/Devices/5B65A8A5-D440-4866-8B9E-D36E74EE5737/data/Containers/Data/Application/3CF93180-E916-4CC0-9D64-92AC31AB8CD0/Pictures
  at XamStorage.iOS.IOSFileSystemFolder.EnsureExists () [0x00022] in <2e6052bd4ec749e9a65cf4e3ae4c0197>:0

**Comment by DuckArne** [comment]
That should not be thrown if you are using WriteAsync().
Must be from where you are creating a folder or trying to get an IFolder.

Check this out https://developer.apple.com/documentation/photokit/requesting_authorization_to_access_photos 

I havent updated and tested anything on a long time. 
Will do so as soon as possible.

**Comment by rex232** [comment]
yes, the error is throw from  CreateFolderAsync if i create custom file or CreateFileAsync when direct saving file to rootfolder

           try
            {
                IFolder rootFolder = await FileSystem.Current.PicturesFolderAsync();
                IFolder folder = await rootFolder.CreateFolderAsync("Funcircle", CreationCollisionOption.ReplaceExisting);


                string fileName = string.Format("{0}.jpg", "profile");
                IFile file = await folder.CreateFileAsync(fileName, CreationCollisionOption.ReplaceExisting);
                await file.WriteAsync(bytes, 0, bytes.Length);

            }
            catch (Exception ex)
            {
             //   Console.WriteLine(ex.ToString());
               // Acr.UserDialogs.UserDialogs.Instance.Toast(ex.ToString());
            } finally  {
              //  Acr.UserDialogs.UserDialogs.Instance.Toast("Success");
            }
            //End save file

**Comment by DuckArne** [comment]
Leaving for vacation like now  so i am going to work on this when i come back next Monday.
Happy easter wishes!

**Comment by rex232** [comment]
Enjoy your holiday :)

在 2019年4月14日 週日 13:26，Mats Andersson <notifications@github.com> 寫道：

**Comment by DuckArne** [comment]
Oki i uploaded a new version on Nuget but i´m afraid that handling create files and save to iOS MusicLibrary is not possible.

Changed so Music, Picture, Photo and VideosFolder is using the Documents folder instead.

Thanks for your issue.
