### ISSUE TITLE
CreateFolderAsync Error

### ISSUE THREAD

**Issue by rex232** [DuckArne/XamStorage.Library#5]
Sorry, its me again.  I got a error when creating folder on IOS, any advise, thanks

 IFolder rootFolder = await FileSystem.Current.PicturesFolderAsync();
 IFolder folder = await rootFolder.CreateFolderAsync("xxx", CreationCollisionOption.ReplaceExisting);
 
![ab652b90-0951-4a40-9fd5-b554272f5793](https://user-images.githubusercontent.com/1892642/58080639-2716a200-7be6-11e9-808a-a98ae2074883.jpg)

**Comment by DuckArne** [comment]
Hi, 
Are you sure your'e on Ver 1.1.3?
Because i can't reproduce the error....
You can check my little test [here](https://github.com/DuckArne/Test.XamStorage)

**Comment by rex232** [comment]
Yes, and only happen on some ios. Now when calling create folder Async and
when the option is replaceifexist, it throw error. Do u think good if add a
try statement on delete folder?

在 2019年5月21日 週二 下午11:15，Mats Andersson <notifications@github.com> 寫道：

**Comment by DuckArne** [comment]
Oki what device or simulator are you running on?
Are you sure it is throwing on CreatefolderAsync()?

**Comment by rex232** [comment]
That is a iphone 6s, running ios 12.1.4.
The log showing last statment is delete folder.

Thanks


在 2019年5月23日 週四 00:46，Mats Andersson <notifications@github.com> 寫道：

**Comment by DuckArne** [comment]
I tested it on several ios phones and i can't reproduce any error.
Need more info.
